name: aoc
version: 0.0.1

ghc-options: -Wall
language: GHC2021

library:
  source-dirs: lib
  dependencies:
    - base
    - bytestring
    - utf8-string
    - http-conduit

executables:
  aoc:
    main: Main.hs
    source-dirs: app
    dependencies:
      - aoc
      - base
      - optparse-applicative

tests:
  spec:
    defaults: hspec/hspec@main
    dependencies:
      - aoc
      - base
      - hspec
