name: aoc
version: 0.0.1

ghc-options: -Wall
language: GHC2021

data-files:
  - data/*

library:
  source-dirs: lib
  dependencies:
    - base
    - megaparsec

executables:
  aoc:
    main: Main.hs
    source-dirs: app
    dependencies:
      - aoc
      - base
      - bytestring
      - directory
      - extra
      - filepath
      - ghc
      - ghc-paths
      - ghc-source-gen
      - http-conduit
      - optparse-applicative
      - process
      - utf8-string

tests:
  spec:
    defaults: hspec/hspec@main
    dependencies:
      - aoc
      - base
      - hspec
